name: clonify
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.10
  firebase_auth: ^0.15.0
  firebase_storage: ^3.1.0
  provider: ^3.1.0
  firebase_storage_image: ^0.4.0
  audioplayers: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/spotify_logo_banner_black.png
    - images/spotify_logo_title.png
    - images/spotify_logo_vertical_black.jpg
    - images/spotify_logo.jpg
    - images/spotify_smaller.png
    - images/Spotify_logo_horizontal_black.jpg

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova/ProximaNovaRegular.ttf
    - family: ProximaNovaBold
      fonts:
        - asset: fonts/ProximaNova/ProximaNovaBold.ttf
